### ISSUE TITLE
Support multiple expandees

### ISSUE THREAD

**Issue by dwijnand** [scalameta/paradise#12]
**build.properties**
```ini
sbt.version=0.13.11
```

**build.sbt**
```scala
scalaVersion := "2.11.8"
addCompilerPlugin("org.scalamacros" % "paradise" % "3.0.0-M3" cross CrossVersion.full)
libraryDependencies += "org.scalameta" %% "scalameta" % "1.0.0"
```

**src/main/scala/p/myann.scala**
```scala
package p

class myann extends scala.annotation.StaticAnnotation {
  inline def apply(defn: Any) = meta { defn }
}
```

**src/test/scala/p/Bippy.scala**
```scala
package p

@myann class Bippy(foo: Int)
object Bippy {
  defaultFoo = 0
}
```

```scala
$ sbt clean test:compile
[info] Compiling 1 Scala source to /s/t/target/scala-2.11/classes...
[info] Compiling 1 Scala source to /s/t/target/scala-2.11/test-classes...
java.lang.RuntimeException: fatal error: multiple expandees not supported at the moment
	at scala.sys.package$.error(package.scala:27)
	at org.scalamacros.paradise.typechecker.Expanders$Expander$class.expand$2(Expanders.scala:101)
	at org.scalamacros.paradise.typechecker.Expanders$Expander$$anonfun$expandNewAnnotationMacro$1.apply(Expanders.scala:162)
	at org.scalamacros.paradise.typechecker.Expanders$Expander$$anonfun$expandNewAnnotationMacro$1.apply(Expanders.scala:162)
	at org.scalamacros.paradise.typechecker.Expanders$Expander$class.extractAndValidateExpansions(Expanders.scala:223)
	at org.scalamacros.paradise.typechecker.Expanders$Expander$class.expandNewAnnotationMacro(Expanders.scala:162)
	at org.scalamacros.paradise.typechecker.Namers$$anon$3.expandNewAnnotationMacro(Namers.scala:13)
	at org.scalamacros.paradise.typechecker.Namers$Namer$$anon$2.org$scalamacros$paradise$typechecker$Namers$Namer$class$$anon$$maybeExpand$1(Namers.scala:370)
	at org.scalamacros.paradise.typechecker.Namers$Namer$$anon$2$$anonfun$7.apply(Namers.scala:377)
	at org.scalamacros.paradise.typechecker.Namers$Namer$$anon$2$$anonfun$7.apply(Namers.scala:377)
	at scala.collection.immutable.Stream.flatMap(Stream.scala:489)
	at org.scalamacros.paradise.typechecker.Namers$Namer$$anon$2.maybeExpand(Namers.scala:377)
	at org.scalamacros.paradise.typechecker.Namers$Namer$MaybeExpandeeCompleter.completeImpl(Namers.scala:322)
	at org.scalamacros.paradise.typechecker.Namers$Namer$MaybeExpandeeCompleter.complete(Namers.scala:312)
	at org.scalamacros.paradise.typechecker.Namers$Namer$RichType.completeOnlyExpansions(Namers.scala:340)
	at org.scalamacros.paradise.typechecker.Expanders$Expander$$anonfun$expandMacroAnnotations$2.apply(Expanders.scala:250)
	at org.scalamacros.paradise.typechecker.Expanders$Expander$$anonfun$expandMacroAnnotations$2.apply(Expanders.scala:243)
	at scala.collection.immutable.List.flatMap(List.scala:327)
	at org.scalamacros.paradise.typechecker.Expanders$Expander$class.expandMacroAnnotations(Expanders.scala:243)
	at org.scalamacros.paradise.typechecker.Expanders$$anon$1.expandMacroAnnotations(Expanders.scala:22)
	at org.scalamacros.paradise.typechecker.AnalyzerPlugins$MacroPlugin$.pluginsEnterStats(AnalyzerPlugins.scala:33)
	at scala.tools.nsc.typechecker.AnalyzerPlugins$$anonfun$pluginsEnterStats$1.apply(AnalyzerPlugins.scala:450)
	at scala.tools.nsc.typechecker.AnalyzerPlugins$$anonfun$pluginsEnterStats$1.apply(AnalyzerPlugins.scala:449)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at scala.tools.nsc.typechecker.AnalyzerPlugins$class.pluginsEnterStats(AnalyzerPlugins.scala:449)
	at org.scalamacros.paradise.typechecker.HijackAnalyzer$$anon$2.pluginsEnterStats(HijackAnalyzer.scala:28)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5011)
... ETC ETC
```

**Comment by iTakeshi** [comment]
@xeno-by Do you have a development roadmap? I'm really looking forward to having this feature implemented in the new generation scala macro.

**Comment by xeno-by** [comment]
Thanks for your interest! I'll be talking more about our plans with scala.meta at Scala By the Bay: http://scala.bythebay.io/.

**Comment by xeno-by** [comment]
Btw this bug may be relatively simple to fix, so if someone would like to give it a try, I'll be glad to give some pointers.

**Comment by iTakeshi** [comment]
Thanks for letting me know about your talk, but unfortunately I won't be able to join the conference because I live in Japan. Plz share your slide in the web.

Also I'm interested in fixing this problem (although I'm just a scala beginner), and I've already read main part of the source of this plugin. So if you give me a pointer, I want to give it a try.

**Comment by xeno-by** [comment]
Sure, I will share the slides. Hope the conference will be recorded, too.

Try converting expandees using toMeta instead of converting and returning just the original (https://github.com/scalameta/paradise/blob/2.11.8/plugin/src/main/scala/org/scalamacros/paradise/typechecker/Expanders.scala#L126).

I'll be travelling tomorrow, so my response time may become quite high. I'll do my best to reply though.

**Comment by iTakeshi** [comment]
Ok, I'll try that.
However I'm busy for other tasks in this weekend, so probably I'll do this on the beginning of the next week. Have a nice trip!

**Comment by iTakeshi** [comment]
At first I wrote some specs for this feature and simply tried to convert each expandee using `toMeta()`
https://github.com/iTakeshi/paradise/commit/fcef0d4648c098699f60cdcc13ae7c6de80b0037
https://github.com/iTakeshi/paradise/commit/63e2b6ad4f9a22f75f3b56b0e5a5e9bcd4fca5bc

Then the `multiple expandees` error has (of course) gone but new error occurred:
```
java.lang.UnsupportedOperationException: Position.point on NoPosition
	at scala.reflect.internal.util.Position.fail(Position.scala:17)
	at scala.reflect.internal.util.UndefinedPosition.point(Position.scala:95)
	at scala.reflect.internal.util.UndefinedPosition.point(Position.scala:90)
	at org.scalamacros.paradise.typechecker.Expanders$Expander$class.captures$1(Expanders.scala:94)
	at org.scalamacros.paradise.typechecker.Expanders$Expander$$anonfun$toMeta$1$1.isDefinedAt(Expanders.scala:97)
	at org.scalamacros.paradise.typechecker.Expanders$Expander$$anonfun$toMeta$1$1.isDefinedAt(Expanders.scala:96)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$3$.apply(Api.scala:19)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$3$.apply(Api.scala:20)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$3$.apply(Api.scala:20)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI.traverse(Api.scala:23)
	at org.scalamacros.paradise.typechecker.Expanders$Expander$class.toMeta$1(Expanders.scala:96)
	at org.scalamacros.paradise.typechecker.Expanders$Expander$$anonfun$4.apply(Expanders.scala:110)
	at org.scalamacros.paradise.typechecker.Expanders$Expander$$anonfun$4.apply(Expanders.scala:109)
...
```

Is this same problem reported in https://github.com/scalamacros/paradise/issues/53 ?
(I couldn't get the point of the discussion and how your "workaround" made a difference.)

I found the `pos: Position` property (or method?) of the `annottee` generated here (https://github.com/scalameta/paradise/blob/2.11.8/plugin/src/main/scala/org/scalamacros/paradise/reflect/TreeInfo.scala#L35) was `NoPosition`, and since this `annottee` was used as the `expandee` the problem was caused.

How can I add proper `pos` to that?

**Comment by iTakeshi** [comment]
UPDATE: I got it!

Please review https://github.com/scalameta/paradise/pull/15, Thanks.

**Comment by xeno-by** [comment]
Fixed in https://github.com/scalameta/paradise/pull/15.
