### ISSUE TITLE
Crash with identity macro when type has companion

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/paradise#205]
Add the below to `Expansion.scala` to reproduce the error

```scala
test("Expansion of type with companion") {
    object SomeObject {
      @identity type A
      object A
    }
  }
```
We need to decide how to handle this.

I believe we should treat type + companion like class + companion.

The original need for this is @alexknvl having some fun with new types.

See https://github.com/alexknvl/newts for the library details.

The actual use case is below

```scala
object Test {
  @opaque type A = Int
  object A { val a = 1 }
}
```

**Comment by xeno-by** [comment]
@DavidDudson Sorry for the late response! Could you post a stack trace here, too? I'm currently afk, but I could suggest where to look if I see the error.

**Comment by DavidDudson** [comment]
@xeno-by This is using jetbrains, but sbt produces the same result.

```


Error:scalac: Error: assertion failed: 
  module A#48728 with maybeExpandeeCompanionCompleter for A#48728
     while compiling: /home/davidd/projects/paradise/tests/meta/src/test/scala/compile/Expansion.scala
        during phase: typer
     library version: version 2.11.11
    compiler version: version 2.11.11
  reconstructed args: -deprecation -feature -Xfatal-warnings -Xplugin:/home/davidd/projects/paradise/plugin/target/scala-2.11/paradise_2.11.11-3.0.0-312-0085993b.jar -unchecked -classpath /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/icedtea-sound.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/management-agent.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/rt.jar:/home/davidd/projects/paradise/tests/meta/target/scala-2.11/test-classes:/home/davidd/projects/paradise/tests/meta/target/scala-2.11/classes:/home/davidd/projects/paradise/tests/common/target/scala-2.11/test-classes:/home/davidd/projects/paradise/tests/common/target/scala-2.11/classes:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalatest/scalatest_2.11/3.0.1/scalatest_2.11-3.0.1.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalameta/trees_2.11/1.8.0/trees_2.11-1.8.0.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalameta/transversers_2.11/1.8.0/transversers_2.11-1.8.0.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalameta/tokens_2.11/1.8.0/tokens_2.11-1.8.0.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalameta/tokenizers_2.11/1.8.0/tokenizers_2.11-1.8.0.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalameta/semantic_2.11/1.8.0/semantic_2.11-1.8.0.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalameta/scalameta_2.11/1.8.0/scalameta_2.11-1.8.0.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalameta/quasiquotes_2.11/1.8.0/quasiquotes_2.11-1.8.0.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalameta/parsers_2.11/1.8.0/parsers_2.11-1.8.0.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalameta/io_2.11/1.8.0/io_2.11-1.8.0.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalameta/inputs_2.11/1.8.0/inputs_2.11-1.8.0.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalameta/inline_2.11/1.8.0/inline_2.11-1.8.0.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalameta/dialects_2.11/1.8.0/dialects_2.11-1.8.0.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalameta/common_2.11/1.8.0/common_2.11-1.8.0.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalactic/scalactic_2.11/3.0.1/scalactic_2.11-3.0.1.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.11/1.0.5/scala-xml_2.11-1.0.5.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.4/scala-parser-combinators_2.11-1.0.4.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.11.11/scala-reflect-2.11.11.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.11/scala-library-2.11.11.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.11.11/scala-compiler-2.11.11.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/com/trueaccord/scalapb/scalapb-runtime_2.11/0.6.0-pre2/scalapb-runtime_2.11-0.6.0-pre2.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/com/trueaccord/lenses/lenses_2.11/0.4.10/lenses_2.11-0.4.10.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/com/lihaoyi/sourcecode_2.11/0.1.3/sourcecode_2.11-0.1.3.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/com/lihaoyi/fastparse_2.11/0.4.3/fastparse_2.11-0.4.3.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/com/lihaoyi/fastparse-utils_2.11/0.4.3/fastparse-utils_2.11-0.4.3.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.2.0/protobuf-java-3.2.0.jar
  last tree to typer: Ident(scala)
       tree position: line 243 of /home/davidd/projects/paradise/tests/meta/src/test/scala/compile/Expansion.scala
            tree tpe: scala.type
              symbol: final package scala
   symbol definition: final package scala (a ModuleSymbol)
      symbol package: <none>
       symbol owners: package scala
           call site: object SomeObject in package <empty>
== Source file context for tree position ==
   240       object A
   241     }
   242   }
   243 }
   244 
   245 // Note: We cannot actually wrap this in test()
   246 // as it cannot be an inner class definition.
java.lang.AssertionError: assertion failed: 
  module A#48728 with maybeExpandeeCompanionCompleter for A#48728
     while compiling: /home/davidd/projects/paradise/tests/meta/src/test/scala/compile/Expansion.scala
        during phase: typer
     library version: version 2.11.11
    compiler version: version 2.11.11
  reconstructed args: -deprecation -feature -Xfatal-warnings -Xplugin:/home/davidd/projects/paradise/plugin/target/scala-2.11/paradise_2.11.11-3.0.0-312-0085993b.jar -unchecked -classpath /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/icedtea-sound.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/management-agent.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/rt.jar:/home/davidd/projects/paradise/tests/meta/target/scala-2.11/test-classes:/home/davidd/projects/paradise/tests/meta/target/scala-2.11/classes:/home/davidd/projects/paradise/tests/common/target/scala-2.11/test-classes:/home/davidd/projects/paradise/tests/common/target/scala-2.11/classes:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalatest/scalatest_2.11/3.0.1/scalatest_2.11-3.0.1.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalameta/trees_2.11/1.8.0/trees_2.11-1.8.0.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalameta/transversers_2.11/1.8.0/transversers_2.11-1.8.0.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalameta/tokens_2.11/1.8.0/tokens_2.11-1.8.0.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalameta/tokenizers_2.11/1.8.0/tokenizers_2.11-1.8.0.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalameta/semantic_2.11/1.8.0/semantic_2.11-1.8.0.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalameta/scalameta_2.11/1.8.0/scalameta_2.11-1.8.0.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalameta/quasiquotes_2.11/1.8.0/quasiquotes_2.11-1.8.0.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalameta/parsers_2.11/1.8.0/parsers_2.11-1.8.0.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalameta/io_2.11/1.8.0/io_2.11-1.8.0.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalameta/inputs_2.11/1.8.0/inputs_2.11-1.8.0.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalameta/inline_2.11/1.8.0/inline_2.11-1.8.0.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalameta/dialects_2.11/1.8.0/dialects_2.11-1.8.0.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalameta/common_2.11/1.8.0/common_2.11-1.8.0.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalactic/scalactic_2.11/3.0.1/scalactic_2.11-3.0.1.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.11/1.0.5/scala-xml_2.11-1.0.5.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.4/scala-parser-combinators_2.11-1.0.4.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.11.11/scala-reflect-2.11.11.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.11/scala-library-2.11.11.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.11.11/scala-compiler-2.11.11.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/com/trueaccord/scalapb/scalapb-runtime_2.11/0.6.0-pre2/scalapb-runtime_2.11-0.6.0-pre2.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/com/trueaccord/lenses/lenses_2.11/0.4.10/lenses_2.11-0.4.10.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/com/lihaoyi/sourcecode_2.11/0.1.3/sourcecode_2.11-0.1.3.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/com/lihaoyi/fastparse_2.11/0.4.3/fastparse_2.11-0.4.3.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/com/lihaoyi/fastparse-utils_2.11/0.4.3/fastparse-utils_2.11-0.4.3.jar:/home/davidd/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.2.0/protobuf-java-3.2.0.jar
  last tree to typer: Ident(scala)
       tree position: line 243 of /home/davidd/projects/paradise/tests/meta/src/test/scala/compile/Expansion.scala
            tree tpe: scala.type
              symbol: final package scala
   symbol definition: final package scala (a ModuleSymbol)
      symbol package: <none>
       symbol owners: package scala
           call site: object SomeObject in package <empty>
== Source file context for tree position ==
   240       object A
   241     }
   242   }
   243 }
   244 
   245 // Note: We cannot actually wrap this in test()
   246 // as it cannot be an inner class definition.
	at scala.tools.nsc.Global.assert(Global.scala:288)
	at org.scalameta.paradise.typechecker.Namers$Namer$MaybeExpandeeCompleter.completeImpl(Namers.scala:344)
	at org.scalameta.paradise.typechecker.Namers$Namer$MaybeExpandeeCompleter.complete(Namers.scala:333)
	at org.scalameta.paradise.typechecker.Namers$Namer$RichType.completeOnlyExpansions(Namers.scala:362)
	at org.scalameta.paradise.typechecker.Expanders$Expander$$anonfun$expandMacroAnnotations$2.apply(Expanders.scala:304)
	at org.scalameta.paradise.typechecker.Expanders$Expander$$anonfun$expandMacroAnnotations$2.apply(Expanders.scala:294)
	at scala.collection.immutable.List.flatMap(List.scala:338)
	at org.scalameta.paradise.typechecker.Expanders$Expander$class.expandMacroAnnotations(Expanders.scala:294)
	at org.scalameta.paradise.typechecker.Expanders$$anon$2.expandMacroAnnotations(Expanders.scala:27)
	at org.scalameta.paradise.typechecker.AnalyzerPlugins$AnalyzerPlugin$.pluginsTypeSig(AnalyzerPlugins.scala:28)
	at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$3$$anonfun$accumulate$3.apply(AnalyzerPlugins.scala:323)
	at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$3$$anonfun$accumulate$3.apply(AnalyzerPlugins.scala:323)
	at scala.tools.nsc.typechecker.AnalyzerPlugins$$anonfun$invoke$1.apply(AnalyzerPlugins.scala:298)
	at scala.tools.nsc.typechecker.AnalyzerPlugins$$anonfun$invoke$1.apply(AnalyzerPlugins.scala:297)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at scala.tools.nsc.typechecker.AnalyzerPlugins$class.invoke(AnalyzerPlugins.scala:297)
	at scala.tools.nsc.typechecker.AnalyzerPlugins$class.pluginsTypeSig(AnalyzerPlugins.scala:321)
	at org.scalameta.paradise.typechecker.HijackAnalyzer$$anon$2.pluginsTypeSig(HijackAnalyzer.scala:31)
	at scala.tools.nsc.typechecker.Namers$Namer.templateSig(Namers.scala:1070)
	at scala.tools.nsc.typechecker.Namers$Namer.moduleSig(Namers.scala:1098)
	at scala.tools.nsc.typechecker.Namers$Namer.getSig$1(Namers.scala:1635)
	at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1650)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply$mcV$sp(Namers.scala:869)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:868)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:868)
	at scala.tools.nsc.typechecker.Namers$Namer.scala$tools$nsc$typechecker$Namers$Namer$$logAndValidate(Namers.scala:1677)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:868)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:860)
	at scala.tools.nsc.typechecker.Namers$$anon$1.completeImpl(Namers.scala:1799)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter$class.complete(Namers.scala:1807)
	at scala.tools.nsc.typechecker.Namers$$anon$1.complete(Namers.scala:1797)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1535)
	at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1680)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5035)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5423)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5450)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5397)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5401)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5481)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:3042)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$65.apply(Typers.scala:3150)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$65.apply(Typers.scala:3150)
	at scala.collection.immutable.List.loop$1(List.scala:176)
	at scala.collection.immutable.List.mapConserve(List.scala:200)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3150)
	at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2376)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typedOutsidePatternMode$1$1.apply(Typers.scala:5345)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typedOutsidePatternMode$1$1.apply(Typers.scala:5345)
	at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:5344)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5380)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5387)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5423)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5450)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5397)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5401)
	at scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:3163)
	at scala.tools.nsc.typechecker.PatternTypers$PatternTyper$class.typedArgWithFormal$1(PatternTypers.scala:112)
	at scala.tools.nsc.typechecker.PatternTypers$PatternTyper$$anonfun$2.apply(PatternTypers.scala:115)
	at scala.tools.nsc.typechecker.PatternTypers$PatternTyper$$anonfun$2.apply(PatternTypers.scala:115)
	at scala.runtime.Tuple2Zipped$$anonfun$map$extension$1.apply(Tuple2Zipped.scala:46)
	at scala.runtime.Tuple2Zipped$$anonfun$map$extension$1.apply(Tuple2Zipped.scala:44)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.runtime.Tuple2Zipped$.map$extension(Tuple2Zipped.scala:44)
	at scala.tools.nsc.typechecker.PatternTypers$PatternTyper$class.typedArgsForFormals(PatternTypers.scala:115)
	at scala.tools.nsc.typechecker.Typers$Typer.typedArgsForFormals(Typers.scala:111)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$handleMonomorphicCall$1(Typers.scala:3469)
	at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3494)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4580)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4608)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5370)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5387)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5423)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5450)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5397)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5401)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5481)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:3042)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$65.apply(Typers.scala:3150)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$65.apply(Typers.scala:3150)
	at scala.collection.immutable.List.loop$1(List.scala:176)
	at scala.collection.immutable.List.mapConserve(List.scala:200)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3150)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1916)
	at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1757)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5336)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5386)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5423)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5450)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5397)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5401)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5481)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:3042)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$65.apply(Typers.scala:3150)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$65.apply(Typers.scala:3150)
	at scala.collection.immutable.List.loop$1(List.scala:176)
	at scala.collection.immutable.List.mapConserve(List.scala:200)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3150)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5042)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5339)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5386)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5423)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5450)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5397)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5401)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5477)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:102)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:467)
	at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:458)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:467)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:94)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:93)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:93)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1528)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1513)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1508)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1609)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:115)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:94)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
	at org.jetbrains.jps.incremental.scala.local.IdeaIncrementalCompiler.compile(IdeaIncrementalCompiler.scala:32)
	at org.jetbrains.jps.incremental.scala.local.LocalServer.compile(LocalServer.scala:26)
	at org.jetbrains.jps.incremental.scala.remote.Main$.make(Main.scala:68)
	at org.jetbrains.jps.incremental.scala.remote.Main$.nailMain(Main.scala:25)
	at org.jetbrains.jps.incremental.scala.remote.Main.nailMain(Main.scala)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
```

**Comment by xeno-by** [comment]
Hmm looks like a tough one. Needs quite some debugging. How urgent is this issue?

**Comment by DavidDudson** [comment]
@xeno-by The fix that is merged into master actually fixes this. 
That may also be the wrong fix and just somehow "work".

It also adds type parameters as companions in the expansion, but I do not believe that is necessary if that is an issue. 

Working with typelevel code, I feel that generating data from types may be a somewhat common operation.

I guess I define companion loosely in the sense that:

The companion of given `Type.Name` is a `Term.Name` with the same string. Regardless of whether that type is from a `Trait`, `Class` or `Type` it's still the same namespace.

I'm quite happy to remove passing any the `Type` with its companions, but if the fix is correct, we will have the issue where it becomes impossible to generate any extra content, given an `Object` of the same name as the type.

In the below example, it is currently possible (With the fix) to modify the `Bar` object based on the `Bar` type. If we remove that, this same macro would crash when encountering an existing `Bar` and would only be able to produce a new `Bar` object.

```scala
@foo type Bar = Int
object Bar {
 def baz: String = ???
}
```

I don't mind if we need to partially revert this change. I still don't see any consequence of this change, but it might make sense as far as the spec is concerned to revert it.

**Comment by xeno-by** [comment]
I think that we can be pretty much satisfied with the current solution. For scalamacros/scalamacros, let's revisit the exact wording of what gets expanded in a macro annotation. Also, the crash is definitely a bug, and we'll have to fix it for scalamacros/scalamacros (since it's likely to use the same expansion-enabling infrastructure).
