### ISSUE TITLE
UnreachableError when rewriting class having annotation on its field

### ISSUE THREAD

**Issue by matwojcik** [scalameta/paradise#210]
When I'm trying to rewrite with meta a class having annotation on its field I get UnreachableError:
```
class MyMeta extends scala.annotation.StaticAnnotation {
  inline def apply(defn: Any): Any = meta {
    defn
  }
}

class MyAnnotation() extends scala.annotation.StaticAnnotation

@MyMeta
case class ExampleClass(@(MyAnnotation @field) id: String)
```

```
org.scalameta.UnreachableError: this code path should've been unreachable
        at org.scalameta.UnreachableError$.raise(package.scala:40)
        at scala.meta.internal.scalahost.converters.LogicalTrees$Parent$.apply(LogicalTrees.scala:1313)
        at scala.meta.internal.scalahost.converters.LogicalTrees$TermNew$.unapply(LogicalTrees.scala:391)
        at scala.meta.internal.scalahost.converters.LogicalTrees$TermSelect$.unapply(LogicalTrees.scala:184)
        at scala.meta.internal.scalahost.converters.ToMtree$toMtree$2$XtensionGtreeToMtree$$anonfun$toMtree$1.apply(ToMtree.scala:52)
        at scala.meta.internal.scalahost.converters.ToMtree$toMtree$2$XtensionGtreeToMtree$$anonfun$toMtree$1.apply(ToMtree.scala:25)
        at scala.meta.internal.scalahost.converters.ToMtree$toMtree$2$.wrap(ToMtree.scala:620)
        at scala.meta.internal.scalahost.converters.ToMtree$toMtree$2$XtensionGtreeToMtree.toMtree(ToMtree.scala:25)
        at scala.meta.internal.scalahost.converters.ToMtree$toMtree$2$XtensionGtreeToMtree$$anonfun$toMtree$1.apply(ToMtree.scala:517)
        at scala.meta.internal.scalahost.converters.ToMtree$toMtree$2$XtensionGtreeToMtree$$anonfun$toMtree$1.apply(ToMtree.scala:25)
        at scala.meta.internal.scalahost.converters.ToMtree$toMtree$2$.wrap(ToMtree.scala:620)
        at scala.meta.internal.scalahost.converters.ToMtree$toMtree$2$XtensionGtreeToMtree.toMtree(ToMtree.scala:25)
        at scala.meta.internal.scalahost.converters.ToMtree$toMtree$2$RichTreesToMtrees$$anonfun$toMtrees$1.apply(ToMtree.scala:606)
        at scala.meta.internal.scalahost.converters.ToMtree$toMtree$2$RichTreesToMtrees$$anonfun$toMtrees$1.apply(ToMtree.scala:606)
        at scala.collection.immutable.List.map(List.scala:284)
        at scala.meta.internal.scalahost.converters.ToMtree$toMtree$2$RichTreesToMtrees.toMtrees(ToMtree.scala:606)
        at scala.meta.internal.scalahost.converters.ToMtree$toMtree$2$XtensionGtreeToMtree$$anonfun$toMtree$1.apply(ToMtree.scala:168)
        at scala.meta.internal.scalahost.converters.ToMtree$toMtree$2$XtensionGtreeToMtree$$anonfun$toMtree$1.apply(ToMtree.scala:25)
        at scala.meta.internal.scalahost.converters.ToMtree$toMtree$2$.wrap(ToMtree.scala:620)
        at scala.meta.internal.scalahost.converters.ToMtree$toMtree$2$XtensionGtreeToMtree.toMtree(ToMtree.scala:25)
        at scala.meta.internal.scalahost.converters.ToMtree$toMtree$2$RichTreesToMtrees$$anonfun$toMtrees$1.apply(ToMtree.scala:606)
        at scala.meta.internal.scalahost.converters.ToMtree$toMtree$2$RichTreesToMtrees$$anonfun$toMtrees$1.apply(ToMtree.scala:606)
        at scala.collection.immutable.List.map(List.scala:284)
        at scala.meta.internal.scalahost.converters.ToMtree$toMtree$2$RichTreesToMtrees.toMtrees(ToMtree.scala:606)
        at scala.meta.internal.scalahost.converters.ToMtree$toMtree$2$RichTreessToMtreess$$anonfun$toMtreess$1.apply(ToMtree.scala:610)
        at scala.meta.internal.scalahost.converters.ToMtree$toMtree$2$RichTreessToMtreess$$anonfun$toMtreess$1.apply(ToMtree.scala:610)
        at scala.collection.immutable.List.map(List.scala:284)
        at scala.meta.internal.scalahost.converters.ToMtree$toMtree$2$RichTreessToMtreess.toMtreess(ToMtree.scala:610)
        at scala.meta.internal.scalahost.converters.ToMtree$toMtree$2$XtensionGtreeToMtree$$anonfun$toMtree$1.apply(ToMtree.scala:471)
        at scala.meta.internal.scalahost.converters.ToMtree$toMtree$2$XtensionGtreeToMtree$$anonfun$toMtree$1.apply(ToMtree.scala:25)
        at scala.meta.internal.scalahost.converters.ToMtree$toMtree$2$.wrap(ToMtree.scala:620)
        at scala.meta.internal.scalahost.converters.ToMtree$toMtree$2$XtensionGtreeToMtree.toMtree(ToMtree.scala:25)
        at scala.meta.internal.scalahost.converters.ToMtree$toMtree$2$XtensionGtreeToMtree$$anonfun$toMtree$1.apply(ToMtree.scala:428)
        at scala.meta.internal.scalahost.converters.ToMtree$toMtree$2$XtensionGtreeToMtree$$anonfun$toMtree$1.apply(ToMtree.scala:25)
        at scala.meta.internal.scalahost.converters.ToMtree$toMtree$2$.wrap(ToMtree.scala:62
```

**Comment by matwojcik** [comment]
Workaround:
```
type MyAnnotation2 = MyAnnotation @field
@MyMeta
case class ExampleClass(@MyAnnotation2 id: String)
```
