### ISSUE TITLE
not compatible with presentation compiler

### ISSUE THREAD

**Issue by fommil** [scalameta/paradise#212]
starting an ENSIME project that uses scalameta paradise gives me this stacktrace

```
akka.actor.ActorInitializationException: akka://ENSIME/user/ensime-main/project/scalac: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:191)
	at akka.actor.ActorCell.create(ActorCell.scala:608)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:462)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:484)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at scala.tools.nsc.plugins.Plugin$.instantiate(Plugin.scala:190)
	at scala.tools.nsc.plugins.Plugins.$anonfun$loadRoughPluginsList$9(Plugins.scala:47)
	at scala.tools.nsc.plugins.Plugins.loadRoughPluginsList(Plugins.scala:47)
	at scala.tools.nsc.plugins.Plugins.loadRoughPluginsList$(Plugins.scala:27)
	at scala.tools.nsc.Global.loadRoughPluginsList(Global.scala:34)
	at scala.tools.nsc.plugins.Plugins.roughPluginsList(Plugins.scala:50)
	at scala.tools.nsc.plugins.Plugins.roughPluginsList$(Plugins.scala:50)
	at scala.tools.nsc.Global.roughPluginsList$lzycompute(Global.scala:34)
	at scala.tools.nsc.Global.roughPluginsList(Global.scala:34)
	at scala.tools.nsc.plugins.Plugins.loadPlugins(Plugins.scala:86)
	at scala.tools.nsc.plugins.Plugins.loadPlugins$(Plugins.scala:56)
	at scala.tools.nsc.Global.loadPlugins(Global.scala:34)
	at scala.tools.nsc.plugins.Plugins.plugins(Plugins.scala:102)
	at scala.tools.nsc.plugins.Plugins.plugins$(Plugins.scala:102)
	at scala.tools.nsc.Global.plugins$lzycompute(Global.scala:34)
	at scala.tools.nsc.Global.plugins(Global.scala:34)
	at scala.tools.nsc.plugins.Plugins.computePluginPhases(Plugins.scala:113)
	at scala.tools.nsc.plugins.Plugins.computePluginPhases$(Plugins.scala:112)
	at scala.tools.nsc.Global.computePluginPhases(Global.scala:34)
	at scala.tools.nsc.Global.computePhaseDescriptors(Global.scala:677)
	at scala.tools.nsc.Global.phaseDescriptors$lzycompute(Global.scala:682)
	at scala.tools.nsc.Global.phaseDescriptors(Global.scala:682)
	at scala.tools.nsc.Global$Run.<init>(Global.scala:1171)
	at scala.tools.nsc.interactive.Global$TyperRun.<init>(Global.scala:1308)
	at scala.tools.nsc.interactive.Global.newTyperRun(Global.scala:1331)
	at scala.tools.nsc.interactive.Global.<init>(Global.scala:286)
	at org.ensime.core.RichPresentationCompiler.<init>(RichPresentationCompiler.scala:315)
	at org.ensime.core.Analyzer.makeScalaCompiler(Analyzer.scala:104)
	at org.ensime.core.Analyzer.preStart(Analyzer.scala:97)
	at akka.actor.Actor.aroundPreStart(Actor.scala:521)
	at akka.actor.Actor.aroundPreStart$(Actor.scala:521)
	at org.ensime.core.Analyzer.aroundPreStart(Analyzer.scala:50)
	at akka.actor.ActorCell.create(ActorCell.scala:591)
	... 9 common frames omitted
Caused by: java.lang.NoSuchFieldException: analyzer
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at org.scalameta.paradise.typechecker.HijackAnalyzer.hijackAnalyzer(HijackAnalyzer.scala:51)
	at org.scalameta.paradise.typechecker.HijackAnalyzer.hijackAnalyzer$(HijackAnalyzer.scala:17)
	at org.scalameta.paradise.Plugin.hijackAnalyzer(Plugin.scala:12)
	at org.scalameta.paradise.Plugin.<init>(Plugin.scala:22)
	... 46 common frames omitted
```

**Comment by xeno-by** [comment]
Looks like one of the flaws of our analyzer hijacking logic. It's good that scalamacros/scalamacros doesn't have this problem.

**Comment by fommil** [comment]
to reproduce, check out https://github.com/frees-io/freestyle and run `sbt tests/test`

or alternatively, consider adding a pcplod test to this project (although that does put pcplod rather low down in the dependency chain of doom)

**Comment by fommil** [comment]
I also can't run ensime on the stalagmite source code because it's using scalameta paradise :cry:

**Comment by fommil** [comment]
@xeno-by could you please give some advice to fix this? I basically can't use ensime when I use `scala.meta` which sucks because I want to use stalagmite and freestyle in my book and it's making it super hard for me to do anything.
