### ISSUE TITLE
NoClassDefFoundError: scala/reflect/internal/Trees

### ISSUE THREAD

**Issue by swachter** [scalameta/paradise#220]
After upgrading to Scala 2.12.2 -> 2.12.3 and Paradise 3.0.0-M9 -> 3.0.0-M10 I get the following error when compiling a project with the net.alchim31.maven/scala-maven-plugin.

Upgrading Scalameta 1.8.0 -> 2.0.0-M1 did not help.

```
[INFO] Compiling 1 source files to /home/was1wa3/bikesensor/log-switch/target/classes at 1501778229692
[INFO] compiler plugin: BasicArtifact(org.scalameta,paradise_2.12.3,3.0.0-M10,null)
[ERROR] java.lang.NoClassDefFoundError: scala/reflect/internal/Trees
[INFO] 	at java.lang.Class.getDeclaredMethods0(Native Method)
[INFO] 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
[INFO] 	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
[INFO] 	at java.lang.Class.getMethod0(Class.java:3018)
[INFO] 	at java.lang.Class.getMethod(Class.java:1784)
[INFO] 	at scala_maven_executions.MainHelper.runMain(MainHelper.java:155)
[INFO] 	at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
```

**Comment by swachter** [comment]
The scala-reflect-2.12.3.jar has not been downloaded properly by Maven (see below). After removing the repository folder and rebuilding everything works fine again.

```
-rw-rw-r--  1 was1wa3 was1wa3  200 Aug  3 18:22 _remote.repositories
-rw-rw-r--  1 was1wa3 was1wa3    0 Aug  3 18:22 scala-reflect-2.12.3.jar
-rw-rw-r--  1 was1wa3 was1wa3  484 Aug  3 18:22 scala-reflect-2.12.3.jar.lastUpdated
-rw-rw-r--  1 was1wa3 was1wa3   40 Aug  3 18:22 scala-reflect-2.12.3.jar.sha1
-rw-rw-r--  1 was1wa3 was1wa3 1804 Aug  3 18:22 scala-reflect-2.12.3.pom
-rw-rw-r--  1 was1wa3 was1wa3  484 Aug  3 18:22 scala-reflect-2.12.3.pom.lastUpdated
-rw-rw-r--  1 was1wa3 was1wa3   40 Aug  3 18:22 scala-reflect-2.12.3.pom.sha1
```
