### ISSUE TITLE
Scalatest compile matcher fails

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/paradise#28]
This passes when used internally (i.e in the macroparadise test package). But fails when used externally (Eg. In my Elysium project (Formerly InlineMacros)).

```scala
class Test extends FunSuite with Matchers {

  test ("Compilation success") {
    "@identity def hi() = 2" should compile
  }
}
```
Error is:
```
/nz/daved/elysium/misc/IdentityTest.scala:8: exception during macro expansion: 
[error] <input>:1: error: expected class or object definition
[error] { @Identity def main() = 2 }
[error] ^
[error] 	at scala.meta.internal.parsers.Reporter$class.syntaxError(Reporter.scala:17)
[error] 	at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:23)
```

I presume this is an SBT configuration issue? Or something else which I'm completely missing.

I'm wondering if it is related to 
What I want out of this ticket is to

A. Figure out what the problem is.
B. Make it work out of the box (via an auto-plugin if necessary)

**Comment by xeno-by** [comment]
Could you provide a full stack trace?

**Comment by DavidDudson** [comment]
```
 	at scala.meta.internal.parsers.Reporter$class.syntaxError(Reporter.scala:17)
[error] 	at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:23)
[error] 	at scala.meta.internal.parsers.Reporter$class.syntaxError(Reporter.scala:18)
[error] 	at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:23)
[error] 	at scala.meta.internal.parsers.ScalametaParser.statSeq(ScalametaParser.scala:3365)
[error] 	at scala.meta.internal.parsers.ScalametaParser.topStatSeq(ScalametaParser.scala:3380)
[error] 	at scala.meta.internal.parsers.ScalametaParser$$anonfun$batchSource$1.apply(ScalametaParser.scala:3616)
[error] 	at scala.meta.internal.parsers.ScalametaParser$$anonfun$batchSource$1.apply(ScalametaParser.scala:3586)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:392)
[error] 	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:398)
[error] 	at scala.meta.internal.parsers.ScalametaParser.batchSource(ScalametaParser.scala:3586)
[error] 	at scala.meta.internal.parsers.ScalametaParser$$anonfun$source$1.apply(ScalametaParser.scala:3571)
[error] 	at scala.meta.internal.parsers.ScalametaParser$$anonfun$source$1.apply(ScalametaParser.scala:3570)
[error] 	at scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:392)
[error] 	at scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:398)
[error] 	at scala.meta.internal.parsers.ScalametaParser.source(ScalametaParser.scala:3569)
[error] 	at scala.meta.internal.parsers.ScalametaParser$$anonfun$parseSource$1.apply(ScalametaParser.scala:155)
[error] 	at scala.meta.internal.parsers.ScalametaParser$$anonfun$parseSource$1.apply(ScalametaParser.scala:155)
[error] 	at scala.meta.internal.parsers.ScalametaParser.parseRule(ScalametaParser.scala:45)
[error] 	at scala.meta.internal.parsers.ScalametaParser.parseSource(ScalametaParser.scala:155)
[error] 	at scala.meta.parsers.Parse$$anonfun$parseSource$1.apply(Parse.scala:31)
[error] 	at scala.meta.parsers.Parse$$anonfun$parseSource$1.apply(Parse.scala:31)
[error] 	at scala.meta.internal.parsers.ScalametaParser$$anon$196.apply(ScalametaParser.scala:3626)
[error] 	at scala.meta.parsers.Api$XtensionParseDialectInput.parse(Api.scala:21)
[error] 	at scala.meta.parsers.Api$XtensionParseInputLike.parse(Api.scala:10)
[error] 	at org.scalamacros.paradise.typechecker.Expanders$Expander$class.expand$2(Expanders.scala:91)
[error] 	at org.scalamacros.paradise.typechecker.Expanders$Expander$$anonfun$expandNewAnnotationMacro$1.apply(Expanders.scala:170)
[error] 	at org.scalamacros.paradise.typechecker.Expanders$Expander$$anonfun$expandNewAnnotationMacro$1.apply(Expanders.scala:170)
[error] 	at org.scalamacros.paradise.typechecker.Expanders$Expander$class.extractAndValidateExpansions(Expanders.scala:231)
[error] 	at org.scalamacros.paradise.typechecker.Expanders$Expander$class.expandNewAnnotationMacro(Expanders.scala:170)
[error] 	at org.scalamacros.paradise.typechecker.Namers$$anon$3.expandNewAnnotationMacro(Namers.scala:13)
[error] 	at org.scalamacros.paradise.typechecker.Namers$Namer$$anon$2.org$scalamacros$paradise$typechecker$Namers$Namer$class$$anon$$maybeExpand$1(Namers.scala:370)
[error] 	at org.scalamacros.paradise.typechecker.Namers$Namer$$anon$2$$anonfun$7.apply(Namers.scala:377)
[error] 	at org.scalamacros.paradise.typechecker.Namers$Namer$$anon$2$$anonfun$7.apply(Namers.scala:377)
[error] 	at scala.collection.immutable.Stream.flatMap(Stream.scala:489)
[error] 	at org.scalamacros.paradise.typechecker.Namers$Namer$$anon$2.maybeExpand(Namers.scala:377)
[error] 	at org.scalamacros.paradise.typechecker.Namers$Namer$MaybeExpandeeCompleter.completeImpl(Namers.scala:322)
[error] 	at org.scalamacros.paradise.typechecker.Namers$Namer$MaybeExpandeeCompleter.complete(Namers.scala:312)
[error] 	at org.scalamacros.paradise.typechecker.Namers$Namer$RichType.completeOnlyExpansions(Namers.scala:340)
[error] 	at org.scalamacros.paradise.typechecker.Expanders$Expander$$anonfun$expandMacroAnnotations$2.apply(Expanders.scala:258)
[error] 	at org.scalamacros.paradise.typechecker.Expanders$Expander$$anonfun$expandMacroAnnotations$2.apply(Expanders.scala:251)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:327)
[error] 	at org.scalamacros.paradise.typechecker.Expanders$Expander$class.expandMacroAnnotations(Expanders.scala:251)
[error] 	at org.scalamacros.paradise.typechecker.Expanders$$anon$1.expandMacroAnnotations(Expanders.scala:22)
[error] 	at org.scalamacros.paradise.typechecker.AnalyzerPlugins$MacroPlugin$.pluginsEnterStats(AnalyzerPlugins.scala:33)
[error] 	at scala.tools.nsc.typechecker.AnalyzerPlugins$$anonfun$pluginsEnterStats$1.apply(AnalyzerPlugins.scala:450)
[error] 	at scala.tools.nsc.typechecker.AnalyzerPlugins$$anonfun$pluginsEnterStats$1.apply(AnalyzerPlugins.scala:449)
[error] 	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
[error] 	at scala.collection.immutable.List.foldLeft(List.scala:84)
[error] 	at scala.tools.nsc.typechecker.AnalyzerPlugins$class.pluginsEnterStats(AnalyzerPlugins.scala:449)
[error] 	at org.scalamacros.paradise.typechecker.HijackAnalyzer$$anon$2.pluginsEnterStats(HijackAnalyzer.scala:28)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2323)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typedOutsidePatternMode$1$1.apply(Typers.scala:5318)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typedOutsidePatternMode$1$1.apply(Typers.scala:5318)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:5317)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5353)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5360)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5396)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5423)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5370)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5374)
[error] 	at scala.reflect.macros.contexts.Typers$$anonfun$typecheckInternal$1$1.apply(Typers.scala:27)
[error] 	at scala.reflect.macros.contexts.Typers$$anonfun$typecheckInternal$1$1.apply(Typers.scala:27)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:680)
[error] 	at scala.reflect.macros.contexts.Typers$class.typecheckInternal$1(Typers.scala:27)
[error] 	at scala.reflect.macros.contexts.Typers$$anonfun$typecheck$2$$anonfun$apply$1.apply(Typers.scala:28)
[error] 	at scala.reflect.macros.contexts.Typers$$anonfun$typecheck$2$$anonfun$apply$1.apply(Typers.scala:28)
[error] 	at scala.reflect.macros.contexts.Typers$$anonfun$3.apply(Typers.scala:24)
[error] 	at scala.reflect.macros.contexts.Typers$$anonfun$3.apply(Typers.scala:24)
[error] 	at scala.reflect.macros.contexts.Typers$$anonfun$withContext$1$1.apply(Typers.scala:25)
[error] 	at scala.reflect.macros.contexts.Typers$$anonfun$withContext$1$1.apply(Typers.scala:25)
[error] 	at scala.reflect.macros.contexts.Typers$$anonfun$1.apply(Typers.scala:23)
[error] 	at scala.reflect.macros.contexts.Typers$$anonfun$1.apply(Typers.scala:23)
[error] 	at scala.reflect.macros.contexts.Typers$class.withContext$1(Typers.scala:25)
[error] 	at scala.reflect.macros.contexts.Typers$$anonfun$typecheck$2.apply(Typers.scala:28)
[error] 	at scala.reflect.macros.contexts.Typers$$anonfun$typecheck$2.apply(Typers.scala:28)
[error] 	at scala.reflect.internal.Trees$class.wrappingIntoTerm(Trees.scala:1716)
[error] 	at scala.reflect.internal.SymbolTable.wrappingIntoTerm(SymbolTable.scala:16)
[error] 	at scala.reflect.macros.contexts.Typers$class.withWrapping$1(Typers.scala:26)
[error] 	at scala.reflect.macros.contexts.Typers$class.typecheck(Typers.scala:28)
[error] 	at scala.reflect.macros.contexts.Context.typecheck(Context.scala:6)
[error] 	at scala.reflect.macros.contexts.Context.typecheck(Context.scala:6)
[error] 	at scala.reflect.macros.Typers$class.typeCheck(Typers.scala:58)
[error] 	at scala.reflect.macros.contexts.Context.typeCheck(Context.scala:6)
[error] 	at org.scalatest.CompileMacro$.checkCompile$1(CompileMacro.scala:687)
[error] 	at org.scalatest.CompileMacro$.assertCompileImpl(CompileMacro.scala:731)
[error] 	at org.scalatest.CompileMacro$.shouldCompileImpl(CompileMacro.scala:775)
```

**Comment by xeno-by** [comment]
Could you rerun the test with the new 3.0.0-SNAPSHOT?

**Comment by DavidDudson** [comment]
Hurray! That works. The code you pushed yesterday must have fixed this. Closing.
